version: '3'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    links:
#      - "db:redis"
      - redis
#  db:
#    image: "redis:alpine"
#    hostname: redis
#    ports:
#      - "6379:6379"
  redis:
    image: redis