version: '3'
services:
  app:
    environment:
      - REDIS_URL=redis://redis:6379/
    build: .
    ports:
      - ${PORT}:8080
    depends_on:
      - redis
  redis:
    image: "redis:alpine"
    hostname: redis
    ports:
      - "6379:6379"
